server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create, update, none 추후 update로 변경해야 안사라지겠지
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #모델네임 그대로 쓰겠다

